### ISSUE TITLE
How to setup the plugin using angular???

### ISSUE THREAD

**Issue by venomone** [videojs/videojs-contrib-eme#195]
Please see:

https://stackoverflow.com/questions/77377503/how-to-setup-videojs-contrib-eme-with-angular

**Comment by adrums86** [comment]
Since this is a dead link, `Page not found`, and no other information is provided, I'm going to close this issue. Based on other issues you have created I would also _highly_ suggest reviewing the [Code of Conduct](https://github.com/videojs/video.js/blob/main/CODE_OF_CONDUCT.md) prior to continued participation in the video.js community.
