### ISSUE TITLE
FairPlay WebKitMediaKeyError

### ISSUE THREAD

**Issue by tobiasps** [videojs/videojs-contrib-eme#74]
I'm trying to setup DRM using videojs 7.5, videojs-contrib-eme 3.4.1, Intertrust ExpressPlay, and nginx-vod-module, but I seem to be stuck and I was hoping if somebody in here could push me in the right direction.

I'm currently focusing on FairPlay on Safari 12.0.3 on macOS 10.14.3 using HLS packaging.

The EME seem to fail before trying to retrieve the license but after retrieving the fairplay certificate in the console I see a:
WebKitMediaKeyError, code 6 (MEDIA_KEYERR_DOMAIN), systemCode 4294955461

Does anybody have a hint on what could be wrong, is it the FairPlay certificate or is the HLS response that's causing this.

Here is a minimal example of my setup:
```
var player = videojs('videojs-contrib-eme-player');
player.src({
    src: hlsUrl,
    type: 'application/x-mpegURL',
    keySystems: {
        "com.apple.fps.1_0": {
            certificateUri: "files/fairplay.cer",
            getLicense: function (emeOptions, contentId, keyMessage, callback) {
                videojs.xhr({
                    uri: licenseUrl,
                    method: 'POST',
                    responseType: 'arraybuffer',
                    body: keyMessage,
                    headers: {
                        'Content-type': 'application/octet-stream',
                        'utoken-drm': 'fp'
                    }
                }, function (err, response, responseBody) {
                    if (err) {
                        callback(err);
                        return;
                    }

                    callback(null, responseBody);
                });
            }
        }
    }
});
```

**Comment by tobiasps** [comment]
Okay, I was lead to believe by the ExpressPlay documentation that I had to define HLS EXT-X-VERSION to 5 or higher. But I just tried setting it back to 1 and now I do not get the above error and I now see the play requesting the license.

I'm closing this issue. Sorry for the noise.

**Comment by Dardaxe** [comment]
Hi @tobiasps,
I'm getting the almost same error as you had :

Using Video.js 7.5.3 and contrib-eme 3.5, Safari 12.1 on macOS 10.14.4, HLS packaging.
Correctly retrieving fairplay certificate but getting
VIDEOJS: – "ERROR:" – "(CODE:5 MEDIA_ERR_ENCRYPTED)" – "The operation is not supported."
and 
VIDEOJS: – "ERROR:" – "(CODE:5 MEDIA_ERR_ENCRYPTED)" – "KeySession error: code 6, systemCode 4294924646
![image](https://user-images.githubusercontent.com/9088465/55802608-df760400-5ad8-11e9-84dc-02266d288160.png)

My GetLicense implementation is close to yours : 
```
"com.apple.fps.1_0": {
   //getCertificate implementation
   getLicense: function(emeOptions, contentId, keyMessage, callback) {
      videojs.xhr({
      url: licenseURL,
      method: 'POST',
      responseType: 'arraybuffer',
      body: keyMessage,
      headers: {
         'Content-type': 'application/octet-stream',
         'customHeader': someCustomData
      }
   }, (err, response, responseBody) => {
      if (err) {
         callback(err)
         return
      }
      callback(null, responseBody)
      })
   }
}
```

I've tried to modify HLS EXT-X-VERSION as you explained and tried every EXT-X-VERSION existing but without success.
Are you sure that you set the EXT-X-VERSION to 1 ? because in the apple documentation this value doesn't seems to exist : 
![image](https://user-images.githubusercontent.com/9088465/55802091-cb7dd280-5ad7-11e9-8e0e-b51a2958a3f9.png)
source : https://developer.apple.com/library/archive/qa/qa1752/_index.html

Do you have an idea on what could be wrong or something else you did that fixed it ?

**Comment by Dardaxe** [comment]
Hey @tobiasps,

I've deliberately omitted the FairPlay certificate part since it works perfectly.

Oh I see, I think you're talking about the _KEYFORMATVERSIONS_ and not the _EXT-X-VERSION_ value of the manifest.

Actually I'm using AWS MediaConvert as packager and DRMToday as DRM Provider.
I think I'm going to create a new issue since our errors are not exactly the same, hoping that someone can help me.

Thanks again for your quick answer !

**Comment by alastairmccormack** [comment]
This is caused by the HLS media playlist not having `KEYFORMAT="com.apple.streamingkeydelivery"` set on the `#EXT-X-KEY` parameter.

In AWS MediaConvert, you can't set this in the GUI. If you're using StaticKey, you need to import a job JSON with `keyFormat` attribute set:

 ```
"StaticKeyProvider": {
    "StaticKeyValue": "FF",
    "Url": "skd://",
    "keyFormat": "com.apple.streamingkeydelivery"
}
```
